bower install --save angular 
bower install --save angular-animate
bower install --save angular-cookies 
bower install --save angular-resource 
bower install --save angular-sanitize
bower install --save angular-ui-router 
bower install --save requirejs 
bower install --save requirejs-text 
bower install --save angularAMD