bower install --save crossroads
bower install --save hasher
bower install --save requirejs
bower install --save requirejs-text
bower install --save knockout
bower install --save Knockout-Validation
bower install --save knockout-projections
bower install --save jquery#1.11.1
bower install --save knockout.mapping